# Generated by Django 4.2.1 on 2023-05-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogtheme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightclaim',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='footerheading',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nav_menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nav_menu',
            name='your_menu',
            field=models.CharField(choices=[('menu1', 'menu1'), ('menu2', 'menu2'), ('menu3', 'menu3'), ('menu4', 'menu4'), ('menu5', 'menu5'), ('menu6', 'menu6')], default='icon1', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='nav_social_media_icon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='navlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
