# Generated by Django 4.2.1 on 2023-05-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0008_auto_20220113_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
